package com.example.motivationalmornings.ui.theme

import androidx.compose.ui.graphics.Color

val MorningSky = Color(0xFFFDF8F5)
val MorningSurface = Color(0xFFFFFBFA)
val MorningPrimary = Color(0xFF9E7C6A)
val MorningOnPrimary = Color(0xFFFFFFFF)
val MorningPrimaryContainer = Color(0xFFF2E4DE)
val MorningOnPrimaryContainer = Color(0xFF321B12)
val MorningSecondary = Color(0xFF85746C)
val MorningOnSecondary = Color(0xFFFFFFFF)
val MorningSecondaryContainer = Color(0xFFF2E4DE)
val MorningOnSecondaryContainer = Color(0xFF211A16)
val MorningTertiary = Color(0xFF948A74)
val MorningOnTertiary = Color(0xFFFFFFFF)
val MorningTertiaryContainer = Color(0xFFEBE4D3)
val MorningOnTertiaryContainer = Color(0xFF1D1B16)
val MorningOutline = Color(0xFF85746C)

val DawnPrimary = Color(0xFFC9A694)
val DawnOnPrimary = Color(0xFF321B12)
val DawnPrimaryContainer = Color(0xFF4D3930)
val DawnOnPrimaryContainer = Color(0xFFF2E4DE)
val DawnSecondary = Color(0xFFA6978E)
val DawnOnSecondary = Color(0xFF282320)
val DawnSecondaryContainer = Color(0xFF3F3935)
val DawnOnSecondaryContainer = Color(0xFFE8E0DB)
val DawnTertiary = Color(0xFFB6A792)
val DawnOnTertiary = Color(0xFF2D2921)
val DawnTertiaryContainer = Color(0xFF444038)
val DawnOnTertiaryContainer = Color(0xFFEBE4D3)
val DawnBackground = Color(0xFF1A1716)
val DawnOnBackground = Color(0xFFEDE6E2)
val DawnSurface = Color(0xFF211D1C)
val DawnOnSurface = Color(0xFFEDE6E2)