package com.example.motivationalmornings.ui.theme

import androidx.compose.ui.graphics.Color

val MorningSky = Color(0xFFFFF6EC)
val MorningSurface = Color(0xFFFFFBF5)
val MorningPrimary = Color(0xFFE17C45)
val MorningOnPrimary = Color(0xFFFFFFFF)
val MorningPrimaryContainer = Color(0xFFFFDCC8)
val MorningOnPrimaryContainer = Color(0xFF4A1B00)
val MorningSecondary = Color(0xFF8F674A)
val MorningOnSecondary = Color(0xFFFFFFFF)
val MorningSecondaryContainer = Color(0xFFFFDCC7)
val MorningOnSecondaryContainer = Color(0xFF321A0B)
val MorningTertiary = Color(0xFFCC8B2E)
val MorningOnTertiary = Color(0xFFFFFFFF)
val MorningTertiaryContainer = Color(0xFFFFE0B6)
val MorningOnTertiaryContainer = Color(0xFF2E1700)
val MorningOutline = Color(0xFF8D6E59)

val DawnPrimary = Color(0xFFFFB98B)
val DawnOnPrimary = Color(0xFF4D2400)
val DawnPrimaryContainer = Color(0xFF6A340E)
val DawnOnPrimaryContainer = Color(0xFFFFDCC8)
val DawnSecondary = Color(0xFFE8C0A5)
val DawnOnSecondary = Color(0xFF422919)
val DawnSecondaryContainer = Color(0xFF5A3F2E)
val DawnOnSecondaryContainer = Color(0xFFFFDCC7)
val DawnTertiary = Color(0xFFFFC570)
val DawnOnTertiary = Color(0xFF472900)
val DawnTertiaryContainer = Color(0xFF643D00)
val DawnOnTertiaryContainer = Color(0xFFFFE0B6)
val DawnBackground = Color(0xFF1E1A18)
val DawnOnBackground = Color(0xFFF5EDE7)
val DawnSurface = Color(0xFF2A2421)
val DawnOnSurface = Color(0xFFF5EDE7)